# -*- coding: utf-8 -*-
"""image_to_pixel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PcNeLZngM3Ymb9vNbRuoUdvI-0gWGIAG
"""

from google.colab import drive
import os
import cv2
import numpy as np
import pandas as pd

drive.mount('/content/drive')

os.chdir('/content/drive/My Drive/PIC16B_PROJ/CollectedImages')

def image_processing(folder_dir, letter):

    """
    Cleaning the images and creating a dataframe of image features

    Arguments to function:
    - folder_dir: path to the directory containing images
    - letter: letter being assign to each image in the dataframe

    Returns:
    - df: dataframe containing flattened arrays of processed images
    """

    # Initialize an empty DataFrame
    df = pd.DataFrame()

    # Loop through the images in the directory
    for filename in os.listdir(folder_dir):
        # Check if the file ends with .jpg
        if filename.endswith(".jpg"):
            # Read the image
            image_path = os.path.join(folder_dir, filename)
            letter_img = cv2.imread(image_path)

            letter_gray = cv2.cvtColor(letter_img, cv2.COLOR_BGR2GRAY)

            # Resize the image
            letter_gray = cv2.resize(letter_gray, (28, 28), interpolation=cv2.INTER_LINEAR)

            # Convert the image to a NumPy array
            np_array = np.array(letter_gray)

            # Flatten the array
            flattened_array = np_array.flatten()

            # Append the flattened array to the DataFrame
            df = df.append(pd.Series(flattened_array), ignore_index=True)

    # Add a column with the specified letter for all rows
    df['Letter'] = letter

    return df

folder_dir = '/content/drive/My Drive/PIC16B_PROJ/CollectedImages/d'
letter = 'D'

sign_D = image_processing(folder_dir, letter)
print(sign_D)

folder_dir = '/content/drive/My Drive/PIC16B_PROJ/CollectedImages/e'
letter = 'E'

sign_E = image_processing(folder_dir, letter)
print(sign_E)

folder_dir = '/content/drive/My Drive/PIC16B_PROJ/CollectedImages/h'
letter = 'H'

sign_H = image_processing(folder_dir, letter)
print(sign_H)

folder_dir = '/content/drive/My Drive/PIC16B_PROJ/CollectedImages/l'
letter = 'L'

sign_L = image_processing(folder_dir, letter)
print(sign_L)

folder_dir = '/content/drive/My Drive/PIC16B_PROJ/CollectedImages/o'
letter = 'O'

sign_O = image_processing(folder_dir, letter)
print(sign_O)

folder_dir = '/content/drive/My Drive/PIC16B_PROJ/CollectedImages/r'
letter = 'r'

sign_R = image_processing(folder_dir, letter)
print(sign_R)

folder_dir = '/content/drive/My Drive/PIC16B_PROJ/CollectedImages/w'
letter = 'W'

sign_W = image_processing(folder_dir, letter)
print(sign_W)

new = sign_D.append(sign_E)
new = new.append(sign_H)
new = new.append(sign_L)
new = new.append(sign_O)
new = new.append(sign_R)
new = new.append(sign_W)

new.to_csv('sign_language_dataset.csv')

sign_language_url = "https://raw.githubusercontent.com/emilyrshi/PIC16B_Project_Repo/6e27757ed9a716812ef7acfc855be8521285a464/SignLanguage_CSV/sign_language_dataset.csv"

sign_language_data = pd.read_csv(sign_language_url, index_col = False)
sign_language_data.head()